/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Mateusz Szuła
 *
 * src/platform/ps2/system_ps2.c — PS2 process lifecycle + device bring-up.
 *
 * The IOP fileio stack bring-up (reset IOP, load iomanX/fileXio/cdfs/audsrv/
 * mc/usb/mouse IRX from EE RAM, fileXioInit, sceCdInit), the lazy USB-mass
 * mount, the USB HID mouse, the PINE bring-up trace, and the system HAL hooks
 * (plat_system_early_init/exit + plat_dcache_flush + plat_trace_mark). Built
 * only for TARGET=ps2. */

#include <stdint.h>

#ifdef WACKI_PS2

#include <sifrpc.h>
#include <loadfile.h>
#include <iopcontrol.h>
#include <sbv_patches.h>
#include <libcdvd.h>
#include <kernel.h>
#include <ps2mouse.h>       /* mouse_data + PS2MOUSE_* constants */
#include <libmouse.h>       /* PS2MouseInit / PS2MouseRead / ... */
#include <libpad.h>         /* DualShock analog-mode kick for plat_pad_read_extra */

#include "wacki/platform/system.h"   /* plat_system_* / dcache / trace / volume */
#include "wacki/platform/input.h"    /* plat_handle_platform_key, plat_pad_read_extra */
#include "wacki/platform/video.h"    /* plat_apply_video_prefs */
#include "ps2_internal.h"            /* platform_ps2_mount_usb (defined here) */

/* The bin2c-embedded IOP modules (generated by tools/build-ps2.sh into
 * /tmp/embed, -I'd onto the include path). Loaded in io_init / mount_usb. */
#include "iomanX_irx.c"
#include "fileXio_irx.c"
#include "cdfs_irx.c"
#include "audsrv_irx.c"
#include "usbd_irx.c"
#include "ps2mouse_irx.c"
#include "bdm_irx.c"
#include "bdmfs_fatfs_irx.c"
#include "usbmass_bd_irx.c"

/* Hand-declared to dodge ps2sdk's guarded fileXio_rpc.h. */
extern int fileXioInit(void);
extern int fileXioDopen(const char *name);   /* USB mount-ready probe */
extern int fileXioDclose(int fd);

/* ---- bring-up trace (read over PINE) ----------------------------- */

volatile uint32_t g_ps2_trace[32];
volatile uint32_t g_ps2_trace_n = 0;
void ps2_mark(uint32_t code)
{
    uint32_t i = g_ps2_trace_n;
    if (i < 32) g_ps2_trace[i] = code;
    g_ps2_trace_n = i + 1;
}

void ps2_spin_forever(void)
{
    for (;;) { }
}

/* ---- file I/O bring-up ------------------------------------------- */

/* Called first thing in WackiMain, before any file access. */
void platform_ps2_io_init(void)
{
    SifInitRpc(0);

    /* Clean IOP — real iomanX/fileXio mustn't fight PCSX2's HLE defaults. */
    while (!SifIopReset("", 0)) { }
    while (!SifIopSync())       { }
    SifInitRpc(0);
    SifLoadFileInit();

    /* Allow loading IRX modules from EE RAM buffers on the reset IOP. */
    sbv_patch_enable_lmb();
    sbv_patch_disable_prefix_check();

    int ret;
    SifExecModuleBuffer(iomanX_irx,  size_iomanX_irx,  0, NULL, &ret);
    SifExecModuleBuffer(fileXio_irx, size_fileXio_irx, 0, NULL, &ret);
    fileXioInit();

    sceCdInit(SCECdINIT);
    SifExecModuleBuffer(cdfs_irx, size_cdfs_irx, 0, NULL, &ret);

    /* Audio: the SPU2 driver (LIBSD, in rom0) + audsrv. Used by the
     * mixer→audsrv thread in platform_ps2_audio_init(). */
    SifLoadModule("rom0:LIBSD", 0, NULL);
    SifExecModuleBuffer(audsrv_irx, size_audsrv_irx, 0, NULL, &ret);

    /* USB HID mouse: the USB host driver + the ps2mouse HID driver. A USB
     * mouse then drives the cursor (a natural fit for point-and-click).
     * usbd must precede ps2mouse, which binds onto it. */
    SifExecModuleBuffer(usbd_irx,     size_usbd_irx,     0, NULL, &ret);
    SifExecModuleBuffer(ps2mouse_irx, size_ps2mouse_irx, 0, NULL, &ret);

    /* NOTE: do NOT call init_joystick_driver() here — SDL2-PS2's
     * SDL_InitSubSystem(GAMECONTROLLER) brings the pad up itself (loads
     * padman), and loading it a second time here conflicts and kills pad
     * input entirely. The pad already works via SDL. */
}

/* ---- USB mass storage (game data off a USB stick on real HW) ------ *
 *
 * On PCSX2 the data lives on HostFS (host:) or the ISO (cdfs:). On a real
 * console booted from USB (uLaunchELF → mass:/wacki.elf) neither exists —
 * the data sits on the same stick under mass:/wacki/data/. The IOP reset in
 * io_init drops uLaunchELF's USB driver, so bring our own BDM FAT stack up
 * (usbd is already loaded for the mouse) and wait for the drive to
 * re-enumerate + mount mass:. Lazy + cached: FindDataRoot only calls this
 * after host:/cdfs: miss, so PCSX2 / disc boots never pay the cost. */
int platform_ps2_mount_usb(void)
{
    static int s_usb = -1;            /* -1 untried, 0 absent, 1 mounted */
    if (s_usb >= 0) return s_usb;

    int ret;
    SifExecModuleBuffer(bdm_irx,         size_bdm_irx,         0, NULL, &ret);
    SifExecModuleBuffer(bdmfs_fatfs_irx, size_bdmfs_fatfs_irx, 0, NULL, &ret);
    SifExecModuleBuffer(usbmass_bd_irx,  size_usbmass_bd_irx,  0, NULL, &ret);

    /* The stack enumerates + mounts mass: asynchronously a beat later. Poll
     * the root dir until it opens (each fileXioDopen is a SIF RPC, and the
     * crude inner delay stretches the wait to a few seconds before giving
     * up — enough for USB enumeration on real hardware). */
    for (int i = 0; i < 1000; ++i) {
        int fd = fileXioDopen("mass:/");
        if (fd >= 0) { fileXioDclose(fd); s_usb = 1; return 1; }
        for (volatile int d = 0; d < 300000; ++d) { /* ~ms-scale spin */ }
    }
    s_usb = 0;
    return 0;
}

/* ---- USB HID mouse ----------------------------------------------- *
 *
 * usbd + ps2mouse (loaded in io_init) expose a USB mouse. Read in DIFF
 * (relative) mode so the per-frame delta folds into the same virtual cursor
 * the pad drives — an idle mouse contributes nothing, so the two coexist.
 * Buttons are edge-detected into single clicks (BTN1 = left = walk/interact,
 * BTN2 = right = toggle actor). plat_pad_read_extra() (below) folds it into
 * the gamepad cursor read. Returns 1 once the mouse stack is up. */
static int      s_mouse_state = -1;  /* -1 untried, 0 unavailable, 1 ready */
static uint32_t s_mouse_btn   = 0;   /* previous button mask (edge detect) */

int platform_ps2_mouse_poll(int *dx, int *dy, int *lmb_edge, int *rmb_edge)
{
    *dx = *dy = 0;
    *lmb_edge = *rmb_edge = 0;

    if (s_mouse_state < 0) {
        /* PS2MouseInit returns 1 (bound) or 0 (already bound) on success,
         * -1 on RPC-bind failure. */
        if (PS2MouseInit() >= 0) {
            PS2MouseSetReadMode(PS2MOUSE_READMODE_DIFF);
            s_mouse_state = 1;
        } else {
            s_mouse_state = 0;       /* RPC bind failed — give up quietly */
        }
    }
    if (s_mouse_state != 1) return 0;

    mouse_data md = { 0, 0, 0, 0 };
    if (PS2MouseRead(&md) <= 0) return 1;   /* no new packet — hold button state */

    *dx = md.x;
    *dy = md.y;
    if ((md.buttons & PS2MOUSE_BTN1) && !(s_mouse_btn & PS2MOUSE_BTN1)) *lmb_edge = 1;
    if ((md.buttons & PS2MOUSE_BTN2) && !(s_mouse_btn & PS2MOUSE_BTN2)) *rmb_edge = 1;
    s_mouse_btn = md.buttons;
    return 1;
}
/* ---- process-lifecycle HAL (wacki/platform/system.h) ------------- */

void plat_system_early_init(void)
{
    /* Bring up the IOP fileio stack BEFORE any file access — ps2sdk's newlib
     * fopen reaches no device, so cygio reads everything through fileXio. */
    platform_ps2_io_init();
    ps2_mark(0x0001u);
}

void plat_system_exit(int rc)
{
    /* Stamp the exit code and PARK the EE so PINE can read the trace
     * breadcrumbs — a returned main() reboots PCSX2 to the BIOS browser and
     * tears down the game PINE needs to talk to. Never returns. */
    ps2_mark(0xE000u | (unsigned)(rc & 0xFFF));
    ps2_spin_forever();
}

/* The EE data cache sits in front of fileXio's DMA into EE RAM; flush the
 * span the producer wrote so the audio feeder thread reads fresh bytes. */
void plat_dcache_flush(void *p, unsigned int n) { SyncDCache(p, (uint8_t *)p + n); }

void plat_trace_mark(unsigned int code) { ps2_mark(code); }

/* ---- platform hooks the SDL input/audio/video layer calls -------- *
 *
 * The PS2 provides the one hooks set for its target. Only the gamepad extras
 * are non-trivial; the rest don't apply (no firmware volume / keysym buttons /
 * windowed mode here). */

/* SDL2-PS2's joystick backend never puts the DualShock into analog mode, so
 * the SDL axes read 0 until we request it via libpad. And a USB HID mouse (if
 * present) folds its relative delta + clicks on top of the stick. Called from
 * the SDL gamepad read (gamepad_sdl.c) every frame. */
#define PS2_MOUSE_SENS 1.0f
void plat_pad_read_extra(float *ax, float *ay)
{
    static int s_analog_set = 0;
    if (!s_analog_set && padGetState(0, 0) == PAD_STATE_STABLE &&
        padSetMainMode(0, 0, PAD_MMODE_DUALSHOCK, PAD_MMODE_LOCK) == 1)
        s_analog_set = 1;                /* takes a few frames to apply */

    extern uint8_t g_lmb_clicked, g_rmb_clicked;
    int mdx = 0, mdy = 0, ml = 0, mr = 0;
    if (platform_ps2_mouse_poll(&mdx, &mdy, &ml, &mr)) {
        *ax += (float)mdx * PS2_MOUSE_SENS;
        *ay += (float)mdy * PS2_MOUSE_SENS;
        if (ml) g_lmb_clicked = 1;
        if (mr) g_rmb_clicked = 1;
    }
}

void plat_restore_system_volume(void)    { }
int  plat_handle_platform_key(int sym)   { (void)sym; return 0; }
void plat_apply_video_prefs(void)        { }
int  plat_input_has_keyboard(void)       { return 0; }   /* DualShock, no kbd */

#endif /* WACKI_PS2 */
