/*
 * save.c — Wacki.sav read / write / slot restore.
 *
 * Original addresses:
 * LoadSaveStateOrInitialize 0x0040A5C0
 * LoadSaveSlot 0x0040BE00
 *
 * The on-disk file is a verbatim dump of the in-memory `g_save` (0x1E0C0 B).
 */
#include "wacki.h"
#include <string.h>
#include <stdio.h>

/* in-memory image */
WackiSaveFile g_save;                          /* */

/* world-state default template (0x999 dwords = 0x2664 B) — RE'd as
 * . In a real port this is generated by reading the original. */
extern const uint8_t g_default_world_state[0x2664];

extern uint32_t  g_script_vars[];
extern uint16_t  g_active_actor;
extern uint16_t  g_cur_etap;
extern uint16_t  g_cur_komnata;
extern uint32_t  g_entity_state[0x11C];        /* g_entity_state */
extern uint32_t  g_scene_snapshot[0x1E];       /* g_inventory */
extern int       LoadStage(uint16_t stage);

/* ------------------------------------------------------------------------- *
 * LoadSaveStateOrInitialize — 0x0040A5C0
 * ------------------------------------------------------------------------- */
void LoadSaveStateOrInitialize(void)
{
    FILE *fp = fopen(WACKI_SAVE_FILE, "rb");
    int loaded = 0;

    if (fp) {
        if (fread(&g_save, 1, sizeof g_save, fp) == sizeof g_save &&
            g_save.magic == WACKI_SAVE_MAGIC)
            loaded = 1;
        fclose(fp);
    }

    if (!loaded) {
        memset(&g_save, 0, sizeof g_save);
        g_save.magic = WACKI_SAVE_MAGIC;
        /* First-launch defaults. T129 originally seeded sound_on=0 to
         * match the original engine (the 1997 build shipped with SFX
         * muted on first launch and required the user to toggle Solund
         * → SFX-on to hear them). The port has NO Solund button wired
         * to sound_on (only music/voice/subtitles/dialogues/extra),
         * so a fresh-install user has no way to enable SFX from inside
         * the game. Default to 1 so SFX work out of the box; users who
         * want the original mute behavior can edit Wacki.sav byte 5. */
        g_save.settings = (WackiSettings){
            .video_mode = 1, .sound_on = 1, .music_on = 1, .pad0 = 0,
            .voice_on = 1, .subtitles_on = 1, .dialogues_on = 1, .pad1 = 0
        };
        for (int i = 0; i < WACKI_SAVE_SLOTS; ++i) {
            WackiSlot *s = &g_save.slots[i];
            memcpy(s->world_default_snapshot,
                   g_default_world_state, sizeof s->world_default_snapshot);
            memcpy(s->name, WACKI_DEFAULT_SLOT_NAME,
                   sizeof WACKI_DEFAULT_SLOT_NAME);
        }
    }
}

/* ------------------------------------------------------------------------- *
 * LoadSaveSlot — 0x0040BE00
 *
 * Pour the slot's contents back into the live globals and call
 * LoadStage(etap) to rebuild the world.
 * ------------------------------------------------------------------------- */
int LoadSaveSlot(uint16_t idx)
{
    if (idx >= WACKI_SAVE_SLOTS) return 0;
    WackiSlot *s = &g_save.slots[idx];
    if (s->stage_indicator == 0) return 0;

    /* T102 call order:
 * 1. g_cur_etap = slot.etap_id
 * 2. LoadStage(etap) ← BEFORE memcpy
 * 3. g_cur_komnata = slot.stage_indicator
 * 4. memcpy of script_vars / entity_state / scene_snapshot
 *
 * Earlier port had LoadStage AFTER the memcpy — LoadStage's stage
 * init + entry_script ran AFTER restoring vars and clobbered them
 * back to defaults. Quickload (F9) and menu Load silently dropped
 * all progress flags every time. */
    g_cur_etap = s->etap_id;
    LoadStage(g_cur_etap);
    g_cur_komnata = s->stage_indicator;
    memcpy(g_script_vars,    s->script_vars,    sizeof s->script_vars);
    memcpy(g_entity_state,   s->entity_state,   sizeof s->entity_state);
    memcpy(g_scene_snapshot, s->scene_snapshot, sizeof s->scene_snapshot);
    return 1;
}

/* ------------------------------------------------------------------------- *
 * WriteSaveFile — embedded in RunGameStageLoop (0x0040BEA0), extracted here.
 * ------------------------------------------------------------------------- */
void WriteSaveFile(void)
{
    /* T131 — atomic write via tmp + rename. Earlier port did naive
 * fopen("Wacki.sav", "wb") which TRUNCATES immediately; a crash
 * between open and fwrite (or any partial write) leaves a zero-byte
 * Wacki.sav, and the next launch silently resets to defaults.
 *
 * The original Win32 build had the same flaw — but we improve on
 * the port side: write to "Wacki.sav.tmp" first, fflush+fsync (best
 * effort), then atomically rename over the real file. */
    g_save.magic = WACKI_SAVE_MAGIC;
    const char *tmp_path = WACKI_SAVE_FILE ".tmp";
    FILE *fp = fopen(tmp_path, "wb");
    if (!fp) return;
    size_t written = fwrite(&g_save, 1, sizeof g_save, fp);
    if (written != sizeof g_save) {
        fclose(fp);
        remove(tmp_path);
        fprintf(stderr, "[save] short write (%zu/%zu) — keeping previous save\n",
                written, sizeof g_save);
        return;
    }
    fflush(fp);
    fclose(fp);
    if (rename(tmp_path, WACKI_SAVE_FILE) != 0) {
        fprintf(stderr, "[save] rename(%s → %s) failed — keeping tmp\n",
                tmp_path, WACKI_SAVE_FILE);
    }
}

/* ------------------------------------------------------------------------- *
 * T53 — quicksave / quickload (port extension).
 *
 * Capture current live globals (etap, komnata, script vars, entity state,
 * scene snapshot) into slot N, then write the file. The slot's name
 * gets a timestamp marker so the user can tell quicksaves apart from
 * named saves. Slot 0 is conventionally reserved for the F5/F9 cycle.
 * ------------------------------------------------------------------------- */
int QuickSaveToSlot(uint16_t idx)
{
    if (idx >= WACKI_SAVE_SLOTS) return 0;
    /* Refuse to save when the game isn't actually in-progress (cur_etap
 * == 0 means we're still in the menu). Otherwise the slot would be
 * written with stage_indicator=0 and LoadSaveSlot would reject it. */
    if (g_cur_etap == 0 || g_cur_komnata == 0) return 0;

    WackiSlot *s = &g_save.slots[idx];
    s->stage_indicator = g_cur_komnata;
    s->etap_id         = g_cur_etap;
    memcpy(s->script_vars,    g_script_vars,    sizeof s->script_vars);
    memcpy(s->entity_state,   g_entity_state,   sizeof s->entity_state);
    memcpy(s->scene_snapshot, g_scene_snapshot, sizeof s->scene_snapshot);
    /* Slot name is owned by the caller — the Save menu sets it from the
 * user's inline-edit input (or our auto-generated etap/komnata
 * default), and the F5 quicksave path stamps a "Quick%u" marker
 * before calling us. Don't clobber it here. */

    WriteSaveFile();
    g_stats.total_quicksaves++;             /* T56 */
    fprintf(stderr, "[save] quicksave → slot %u (etap=%u komnata=%u)\n",
            idx, g_cur_etap, g_cur_komnata);
    return 1;
}

int QuickLoadFromSlot(uint16_t idx)
{
    if (idx >= WACKI_SAVE_SLOTS) return 0;
    WackiSlot *s = &g_save.slots[idx];
    if (s->stage_indicator == 0) {
        fprintf(stderr, "[save] quickload slot %u empty — skip\n", idx);
        return 0;
    }
    g_stats.total_quickloads++;             /* T56 */
    fprintf(stderr, "[save] quickload ← slot %u (etap=%u komnata=%u)\n",
            idx, s->etap_id, s->stage_indicator);
    return LoadSaveSlot(idx);
}
